apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crm-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nexus-crm
  source:
    repoURL: https://github.com/nexus-crm/nexus-crm.git
    targetRevision: main
    path: services/crm-service/k8s
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nexus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nexus-crm
  source:
    repoURL: https://github.com/nexus-crm/nexus-crm.git
    targetRevision: main
    path: services/auth-service/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: nexus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
