apiVersion: cilium.io/v2alpha1
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: hubble-visibility
spec:
  endpointSelector: {}
  ingressDeny:
    - {}
  ingress:
    - fromEntities:
        - cluster
  egress:
    - toEntities:
        - cluster
        - world
  visibility:
    - type: http
      port: "80"
    - type: http
      port: "443"
    - type: kafka
      port: "9092"
    - type: dns
      port: "53"
