apiVersion: v1
kind: Namespace
metadata:
  name: nexus
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: nexus-monitoring
  labels:
    istio-injection: enabled
