apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: nexus
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          ports:
            - containerPort: 6379
              name: redis
          command:
            - redis-server
            - --appendonly
            - "yes"
            - --maxmemory
            - "768mb"
            - --maxmemory-policy
            - "allkeys-lru"
            - --tcp-keepalive
            - "60"
            - --timeout
            - "300"
            - --tcp-backlog
            - "511"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: nexus
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
