apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-postgres
  namespace: nexus
spec:
  encryptedData:
    url: AgByA...encrypted...
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-redis
  namespace: nexus
spec:
  encryptedData:
    url: AgByA...encrypted...
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-jwt
  namespace: nexus
spec:
  encryptedData:
    secret: AgByA...encrypted...
