apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nexus-services
  namespace: nexus-monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - nexus
  selector:
    matchLabels:
      app.kubernetes.io/name: nexus-crm
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
