apiVersion: apps/v1
kind: Deployment
metadata:
  name: snyk-monitor
  namespace: nexus-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snyk-monitor
  template:
    metadata:
      labels:
        app: snyk-monitor
    spec:
      serviceAccountName: snyk-monitor
      containers:
        - name: monitor
          image: snyk/kubernetes-monitor:2.11.0
          env:
            - name: SNYK_INTEGRATION_ID
              valueFrom:
                secretKeyRef:
                  name: snyk-integration
                  key: integration-id
            - name: SNYK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: snyk-integration
                  key: api-token
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
