-- Account depth hardening fields added after the initial account baseline.

ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "code" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "legalName" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "tradeName" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "fax" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "subIndustry" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "lifecycleStage" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "foundedYear" INTEGER;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "taxId" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "vatNumber" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "commercialRegistrationNumber" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "paymentTerms" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "creditLimit" DECIMAL(18,2);
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "currency" TEXT DEFAULT 'USD';
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "priceBookId" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "territoryId" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "riskLevel" TEXT DEFAULT 'low';
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "lastActivityAt" TIMESTAMP(3);
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "billingAddressLine1" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "billingAddressLine2" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "billingCity" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "billingState" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "billingPostalCode" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "billingCountry" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "billingLatitude" DOUBLE PRECISION;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "billingLongitude" DOUBLE PRECISION;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "shippingAddressLine1" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "shippingAddressLine2" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "shippingCity" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "shippingState" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "shippingPostalCode" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "shippingCountry" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "shippingLatitude" DOUBLE PRECISION;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "shippingLongitude" DOUBLE PRECISION;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "shippingInstructions" TEXT;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "sameAsBilling" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "Account_tenantId_code_idx" ON "Account"("tenantId", "code");

