apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus-approval.fullname" . }}
  labels:
    {{- include "nexus-approval.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nexus-approval.selectorLabels" . | nindent 4 }}
