export function dealFactory(overrides: Record<string, unknown> = {}) {
  return {
    id: 'dea_' + Math.random().toString(36).slice(2, 11),
    tenantId: 'ten_test',
    ownerId: 'usr_test',
    accountId: 'acc_test',
    pipelineId: 'pip_test',
    stageId: 'stg_test',
    name: 'Test Deal',
    amount: '10000',
    currency: 'USD',
    probability: 50,
    expectedCloseDate: null,
    actualCloseDate: null,
    status: 'OPEN',
    lostReason: null,
    lostDetail: null,
    forecastCategory: 'PIPELINE',
    meddicicScore: 0,
    meddicicData: {},
    competitors: [],
    source: null,
    campaignId: null,
    customFields: {},
    tags: [],
    version: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    ...overrides,
  };
}
