import {
  Activity,
  BarChart2,
  BookOpenText,
  Bot,
  Boxes,
  Briefcase,
  Building2,
  CalendarIcon,
  CheckSquare,
  Compass,
  CreditCard,
  Database,
  DollarSign,
  FileText,
  GitBranch,
  Globe,
  Inbox,
  Layers,
  Lock,
  Mail,
  Map,
  MessageCircle,
  Network,
  Package,
  Percent,
  Recycle,
  Settings2,
  ShoppingCart,
  ShieldCheck,
  Target,
  TrendingUp,
  Trophy,
  Users,
  Webhook,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export type ModuleStatus = 'ready' | 'wired' | 'preview' | 'needs-backend';

export interface CrmModule {
  id: string;
  label: string;
  href: string;
  icon: LucideIcon;
  status: ModuleStatus;
  service: string;
  description: string;
  depth: string[];
  sidebar?: boolean;
  adminOnly?: boolean;
}

export interface CrmModuleGroup {
  id: string;
  label: string;
  icon: LucideIcon;
  description: string;
  modules: CrmModule[];
}

export const CRM_MODULE_GROUPS: CrmModuleGroup[] = [
  {
    id: 'sales',
    label: 'Sales',
    icon: TrendingUp,
    description: 'Lead-to-opportunity execution, pipeline control, forecasting, and quote creation.',
    modules: [
      {
        id: 'dashboard',
        label: 'Dashboard',
        href: '/dashboard',
        icon: Layers,
        status: 'wired',
        service: 'web, crm, analytics',
        description: 'Executive workspace for revenue KPIs, activity, and next actions.',
        depth: ['KPI overview', 'pipeline summary', 'activity signals', 'quick create'],
        sidebar: true,
      },
      {
        id: 'leads',
        label: 'Leads',
        href: '/leads',
        icon: Target,
        status: 'wired',
        service: 'crm-service, leads-service',
        description: 'Lead capture, scoring, qualification, ownership, and conversion.',
        depth: ['qualification state', 'deterministic scoring', 'conversion path', 'owner assignment'],
        sidebar: true,
      },
      {
        id: 'deals',
        label: 'Deals',
        href: '/deals',
        icon: Briefcase,
        status: 'wired',
        service: 'crm-service, deals-service',
        description: 'Opportunity lifecycle, MEDDIC fields, stakeholders, rooms, competitors, and cloning.',
        depth: ['deal rooms', 'stakeholder maps', 'field history', 'discount approvals'],
        sidebar: true,
      },
      {
        id: 'pipeline',
        label: 'Pipeline',
        href: '/pipeline',
        icon: Layers,
        status: 'wired',
        service: 'crm-service',
        description: 'Pipeline board, stages, drag-and-drop movements, and pipeline analytics.',
        depth: ['stage automation', 'pipeline settings', 'analytics view', 'default pipelines'],
        sidebar: true,
      },
      {
        id: 'quotes',
        label: 'Quotes',
        href: '/quotes',
        icon: FileText,
        status: 'wired',
        service: 'quotes-service, finance-service',
        description: 'Quote builder, templates, approvals, PDF generation, and portal sharing.',
        depth: ['template-ready quotes', 'line items', 'portal token sharing', 'PDF export'],
        sidebar: false,
      },
      {
        id: 'forecast',
        label: 'Forecast',
        href: '/forecast',
        icon: Percent,
        status: 'wired',
        service: 'planning-service',
        description: 'Rep and manager forecast submissions, rollups, overrides, and history.',
        depth: ['team rollups', 'manager adjustments', 'forecast history', 'commit tracking'],
        sidebar: true,
      },
      {
        id: 'planning',
        label: 'Planning',
        href: '/planning',
        icon: CalendarIcon,
        status: 'preview',
        service: 'planning-service',
        description: 'Quotas, planning calendars, forecast overrides, and capacity assumptions.',
        depth: ['quota setup', 'period planning', 'team summary', 'override governance'],
        sidebar: true,
      },
    ],
  },
  {
    id: 'quoting',
    label: 'Quoting',
    icon: FileText,
    description: 'One grouped CPQ workspace for RFQs, quotes, DRQs, templates, approvals, documents, e-sign, and order handoff.',
    modules: [
      {
        id: 'quotes-workspace',
        label: 'Quotes',
        href: '/quotes',
        icon: FileText,
        status: 'wired',
        service: 'finance-service, approval-service, document-service',
        description: 'Quote builder, quote expiry, normalized lines, revisions, documents, e-sign, approvals, and order conversion.',
        depth: ['quote expiry', 'line normalization', 'immutable revisions', 'document rendering', 'e-sign lifecycle', 'order handoff'],
        sidebar: true,
      },
      {
        id: 'rfqs-workspace',
        label: 'RFQs',
        href: '/rfqs',
        icon: FileText,
        status: 'wired',
        service: 'finance-service',
        description: 'Request-for-quote capture, account/deal linkage, vendor flow, and conversion to priced quotes.',
        depth: ['account/deal validation', 'vendor response path', 'CPQ conversion', 'status tracking'],
        sidebar: true,
      },
      {
        id: 'drq-workspace',
        label: 'Discount Requests',
        href: '/approvals',
        icon: ShieldCheck,
        status: 'wired',
        service: 'finance-service, approval-service',
        description: 'DRQ approval queue for requested discount, prevalidated reason, approval status, and win probability.',
        depth: ['discount percent', 'reason catalog', 'win probability', 'approval workflow', 'audit events'],
        // Deduped: routes to /approvals, same as the Operations → Approvals item.
        sidebar: false,
      },
      {
        id: 'quote-templates-workspace',
        label: 'Quote Templates',
        href: '/settings/quote-automation',
        icon: Zap,
        status: 'wired',
        service: 'finance-service, document-service',
        description: 'Versioned quote templates, active/default governance, and render/export controls.',
        depth: ['template versions', 'default template', 'PDF/DOCX/HTML render', 'variable catalog'],
        sidebar: true,
      },
    ],
  },
  {
    id: 'customer',
    label: 'Customer',
    icon: Users,
    description: 'Accounts, contacts, activity records, communications, and relationship intelligence.',
    modules: [
      {
        id: 'contacts',
        label: 'Contacts',
        href: '/contacts',
        icon: Users,
        status: 'wired',
        service: 'contacts-service, crm-service',
        description: 'Contact records, duplicate checks, consent records, portal links, and communication history.',
        depth: ['duplicate warnings', 'consent manager', 'portal access', 'WhatsApp thread'],
        sidebar: true,
      },
      {
        id: 'accounts',
        label: 'Accounts',
        href: '/accounts',
        icon: Building2,
        status: 'wired',
        service: 'accounts-service, crm-service',
        description: 'Account hierarchy, health, parent-child structure, and map view.',
        depth: ['hierarchy tree', 'account health', 'map view', 'related contacts/deals'],
        sidebar: true,
      },
      {
        id: 'feed',
        label: 'Following',
        href: '/feed',
        icon: Inbox,
        status: 'wired',
        service: 'crm-service',
        description: 'Recent activity across the accounts and contacts you follow.',
        depth: ['followed records', 'activity feed', 'follow/unfollow', 'record links'],
        sidebar: true,
      },
      {
        id: 'activities',
        label: 'Activities',
        href: '/activities',
        icon: Activity,
        status: 'wired',
        service: 'activities-service, crm-service',
        description: 'Calls, meetings, tasks, notes, and timeline execution.',
        depth: ['call logging', 'owner filters', 'activity timeline', 'task state'],
        sidebar: true,
      },
      {
        id: 'tasks',
        label: 'Tasks',
        href: '/tasks',
        icon: CheckSquare,
        status: 'wired',
        service: 'activities-service, crm-service',
        description: 'Task list, due-date control, priority handling, ownership, and completion workflow.',
        depth: ['task queue', 'priority filters', 'split detail view', 'completion workflow'],
        sidebar: true,
      },
      {
        id: 'calendar',
        label: 'Calendar',
        href: '/calendar',
        icon: CalendarIcon,
        status: 'preview',
        service: 'integration-service',
        description: 'Calendar planning, schedule visibility, and booking workflows.',
        depth: ['calendar views', 'rep scheduling', 'meeting links', 'calendar integrations'],
        sidebar: true,
      },
      {
        id: 'notes',
        label: 'Notes',
        href: '/notes',
        icon: FileText,
        status: 'wired',
        service: 'notes-service',
        description: 'Entity-linked notes, rich text, history, and team capture.',
        depth: ['linked records', 'rich notes', 'searchable context', 'ownership'],
        sidebar: true,
      },
      {
        id: 'documents',
        label: 'Documents',
        href: '/documents',
        icon: FileText,
        status: 'preview',
        service: 'document-service, storage-service',
        description: 'Customer, account, deal, and quote attachments with document lifecycle support.',
        depth: ['entity attachments', 'document preview', 'signature handoff', 'storage metadata'],
        sidebar: true,
      },
    ],
  },
  {
    id: 'product-revenue',
    label: 'Product & Revenue',
    icon: Package,
    description: 'CPQ, product catalog, RFQs, invoices, contracts, commissions, and incentives.',
    modules: [
      {
        id: 'products',
        label: 'Products',
        href: '/products',
        icon: Package,
        status: 'wired',
        service: 'finance-service',
        description: 'Product catalog, kits, vendors, price books, taxes, and CPQ source data.',
        depth: ['products', 'kits', 'vendors', 'price books', 'tax mappings'],
        sidebar: true,
      },
      {
        id: 'cpq',
        label: 'CPQ',
        href: '/settings/quote-automation',
        icon: Zap,
        status: 'wired',
        service: 'finance-service, workflow-service',
        description: 'Quote automation rules, templates, approvals, and downstream document creation.',
        depth: ['rules engine', 'quote templates', 'approval triggers', 'create-quote actions'],
        sidebar: false,
      },
      {
        id: 'invoices',
        label: 'Invoices',
        href: '/invoices',
        icon: FileText,
        status: 'wired',
        service: 'finance-service',
        description: 'Invoice records, PDF output, ZATCA status, and payment state.',
        depth: ['invoice lifecycle', 'PDF generation', 'ZATCA submission', 'tax handling'],
        sidebar: true,
      },
      {
        id: 'contracts',
        label: 'Contracts',
        href: '/contracts',
        icon: CreditCard,
        status: 'wired',
        service: 'finance-service, document-service',
        description: 'Contract records, signature workflow, ownership, and deal linkage.',
        depth: ['contract ownership', 'signature action', 'status control', 'deal linkage'],
        sidebar: true,
      },
      {
        id: 'incentives',
        label: 'Incentives',
        href: '/incentives',
        icon: Trophy,
        status: 'wired',
        service: 'incentive-service',
        description: 'Contests, badges, recognition, and performance incentives.',
        depth: ['badges', 'contests', 'leaderboards', 'award tracking'],
        sidebar: true,
      },
      {
        id: 'commission',
        label: 'Commissions',
        href: '/commission',
        icon: Percent,
        status: 'wired',
        service: 'incentive-service',
        description: 'Commission plans, rate rules, and per-rep commission statements on won deals.',
        depth: ['plans + tiered rules', 'auto-computed on deal.won', 'rep statements', 'approve/pay workflow'],
        sidebar: true,
      },
      {
        id: 'orders',
        label: 'Orders',
        href: '/orders',
        icon: ShoppingCart,
        status: 'wired',
        service: 'finance-service',
        description: 'Sales orders from quote conversion: line items, totals, and invoice generation.',
        depth: ['order list', 'order detail', 'quote/deal linkage', 'create invoice from order'],
        sidebar: true,
      },
    ],
  },
  {
    id: 'analytics-reporting',
    label: 'Analytics & Reporting',
    icon: BarChart2,
    description: 'Reports, dashboards, funnel analysis, leaderboard, competitors, and win/loss intelligence.',
    modules: [
      {
        id: 'reports',
        label: 'Reports',
        href: '/reports',
        icon: FileText,
        status: 'wired',
        service: 'reporting-service',
        description: 'Report center, performance reports, manager reports, builder, and rep drilldowns.',
        depth: ['report builder', 'manager reports', 'performance reports', 'rep drilldowns'],
        sidebar: true,
      },
      {
        id: 'analytics',
        label: 'Analytics',
        href: '/analytics',
        icon: BarChart2,
        status: 'wired',
        service: 'analytics-service, crm-service',
        description: 'Revenue analytics, funnel conversion, snapshots, and trend views.',
        depth: ['snapshot data', 'conversion views', 'dashboard widgets', 'trend analytics'],
        sidebar: true,
      },
      {
        id: 'funnel',
        label: 'Funnel',
        href: '/analytics/funnel',
        icon: TrendingUp,
        status: 'wired',
        service: 'analytics-service',
        description: 'Stage-by-stage conversion, leakage, velocity, and bottleneck discovery.',
        depth: ['stage conversion', 'velocity', 'leakage', 'bottleneck tracking'],
        sidebar: true,
      },
      {
        id: 'win-loss',
        label: 'Win / Loss',
        href: '/analytics/win-loss',
        icon: CheckSquare,
        status: 'wired',
        service: 'crm-service, analytics-service',
        description: 'Closed deal analysis, loss reasons, trendline, revenue split, and action insight.',
        depth: ['loss reasons', 'win-rate trend', 'won/lost revenue', 'period controls'],
        sidebar: true,
      },
      {
        id: 'competitors',
        label: 'Competitors',
        href: '/analytics/competitors',
        icon: ShieldCheck,
        status: 'wired',
        service: 'crm-service',
        description: 'Competitor tracking, win/loss against competitors, and battlecard insight.',
        depth: ['competitor records', 'battlecards', 'deal linkage', 'win/loss comparison'],
        sidebar: true,
      },
      {
        id: 'leaderboard',
        label: 'Leaderboard',
        href: '/analytics/leaderboard',
        icon: Trophy,
        status: 'wired',
        service: 'analytics-service',
        description: 'Rep and team ranking across activity, revenue, and performance signals.',
        depth: ['rep ranking', 'team ranking', 'activity metrics', 'revenue metrics'],
        sidebar: true,
      },
      {
        id: 'reporting',
        label: 'Reporting Workspace',
        href: '/reporting',
        icon: Database,
        status: 'preview',
        service: 'reporting-service',
        description: 'Saved reports, dashboards, schedules, widgets, export, and reporting APIs.',
        depth: ['saved reports', 'dashboards', 'schedules', 'widgets', 'exports'],
        sidebar: true,
      },
    ],
  },
  {
    id: 'operations',
    label: 'Operations',
    icon: Settings2,
    description: 'Process control, approvals, workflows, cadences, journeys, territories, and data operations.',
    modules: [
      {
        id: 'approvals',
        label: 'Approvals',
        href: '/approvals',
        icon: ShieldCheck,
        status: 'wired',
        service: 'approval-service',
        description: 'Approval policies, requests, discount approval, and governance queues.',
        depth: ['approval policies', 'request queues', 'discount approvals', 'audit trail'],
        sidebar: true,
      },
      {
        id: 'workflows',
        label: 'Workflows',
        href: '/workflows',
        icon: GitBranch,
        status: 'wired',
        service: 'workflow-service',
        description: 'Low-code workflow builder, execution engine, nodes, conditions, forks, joins, and SLAs.',
        depth: ['low-code flows', 'execution engine', 'SLA nodes', 'approval nodes', 'validation nodes'],
        sidebar: true,
      },
      {
        id: 'command-center',
        label: 'Journeys',
        href: '/command-center',
        icon: Compass,
        status: 'wired',
        service: 'workflow-service',
        description: 'Lifecycle journey builder: entry triggers, ordered steps, activation, and enrollments.',
        depth: ['entry trigger', 'ordered steps', 'step config', 'activate/archive', 'enrollments'],
        sidebar: true,
      },
      {
        id: 'cadences',
        label: 'Cadences',
        href: '/cadences',
        icon: Zap,
        status: 'wired',
        service: 'cadence-service',
        description: 'Sales sequences, enrollments, timing, and action queues.',
        depth: ['sequence steps', 'enrollment', 'timing', 'action queue'],
        sidebar: true,
      },
      {
        id: 'territories',
        label: 'Territories',
        href: '/territories',
        icon: Map,
        status: 'wired',
        service: 'territory-service',
        description: 'Territory assignment, routing, coverage, and account ownership logic.',
        depth: ['territory routing', 'coverage', 'account assignment', 'rep mapping'],
        sidebar: true,
      },
      {
        id: 'migration',
        label: 'Migration',
        href: '/settings/migration',
        icon: Database,
        status: 'wired',
        service: 'data-service',
        description: 'CSV import, migration jobs, import progress, and data onboarding.',
        depth: ['CSV import', 'job status', 'field mapping', 'data onboarding'],
        sidebar: true,
      },
    ],
  },
  {
    id: 'communications-support',
    label: 'Communications & Support',
    icon: Mail,
    description: 'Email, messaging, templates, outbox, portal, knowledge, and support-facing workspaces.',
    modules: [
      {
        id: 'inbox',
        label: 'Inbox',
        href: '/inbox',
        icon: Inbox,
        status: 'wired',
        service: 'email-sync-service, comm-service',
        description: 'Email connection, inbox, threads, templates, and deal-linked messages.',
        depth: ['email connection', 'threads', 'templates', 'deal email'],
        sidebar: true,
      },
      {
        id: 'whatsapp',
        label: 'Messages',
        href: '/messages/whatsapp',
        icon: MessageCircle,
        status: 'wired',
        service: 'comm-service',
        description: 'WhatsApp send, thread, outbox, and customer communication flows.',
        depth: ['WhatsApp send', 'thread history', 'outbox', 'contact linkage'],
        sidebar: true,
      },
      {
        id: 'knowledge',
        label: 'Knowledge',
        href: '/knowledge',
        icon: BookOpenText,
        status: 'wired',
        service: 'knowledge-service',
        description: 'Knowledge base, articles, authoring, and support content.',
        depth: ['articles', 'new article', 'support content', 'searchable knowledge'],
        sidebar: true,
      },
      {
        id: 'tickets',
        label: 'Tickets',
        href: '/tickets',
        icon: Inbox,
        status: 'ready',
        service: 'ticket-service',
        description: 'Support tickets/cases: SLA policies, queues, assignment, and history.',
        depth: ['ticket queue', 'new ticket', 'SLA tracking', 'comments & history'],
        sidebar: true,
      },
      {
        id: 'campaigns',
        label: 'Campaigns',
        href: '/campaigns',
        icon: Mail,
        status: 'ready',
        service: 'campaign-service',
        description: 'Marketing campaigns: membership, send, engagement tracking, and attribution.',
        depth: ['campaign list', 'new campaign', 'members', 'metrics & attribution'],
        sidebar: true,
      },
      {
        id: 'chatbot',
        label: 'Chatbot',
        href: '/chatbot',
        icon: Bot,
        status: 'preview',
        service: 'chatbot-service',
        description: 'Chatbot channels, conversations, and support automation.',
        depth: ['channel setup', 'conversation list', 'webhook endpoints', 'support automation'],
        sidebar: true,
      },
      {
        id: 'portal',
        label: 'Portal',
        href: '/portal/settings',
        icon: Globe,
        status: 'wired',
        service: 'portal-service',
        description: 'Customer portal settings, deal rooms, quote sharing, and external access.',
        depth: ['portal settings', 'deal room links', 'quote sharing', 'external tokens'],
        sidebar: true,
      },
    ],
  },
  {
    id: 'administration',
    label: 'Administration',
    icon: ShieldCheck,
    description: 'People, access, security, integrations, and workspace administration.',
    modules: [
      {
        id: 'system-map',
        label: 'System Map',
        href: '/system-map',
        icon: Database,
        status: 'ready',
        service: 'web',
        description: 'Full CRM module registry, feature depth, services, and preview status.',
        depth: ['module catalog', 'service mapping', 'feature depth', 'preview health'],
        sidebar: true,
      },
      {
        id: 'settings',
        label: 'Settings',
        href: '/settings',
        icon: Settings2,
        status: 'wired',
        service: 'web',
        description: 'General workspace configuration and user preferences.',
        depth: ['profile', 'team', 'notifications', 'security', 'localization'],
        sidebar: true,
      },
      {
        id: 'integrations',
        label: 'Integrations',
        href: '/settings/integrations',
        icon: Zap,
        status: 'wired',
        service: 'integration-service',
        description: 'Mail, calendar, maps, Slack, Teams, ZATCA, and external ERP integrations.',
        depth: ['mail', 'calendar', 'maps', 'Slack', 'Teams', 'ZATCA'],
        // Deduped: the wired "Connections & Sync" (/integrations) item is the
        // single Integrations entry in the sidebar. Still routable from settings.
        sidebar: false,
      },
      {
        id: 'integration-connections',
        label: 'Connections & Sync',
        href: '/integrations',
        icon: Zap,
        status: 'wired',
        service: 'integration-service',
        description: 'Live OAuth connections, scopes, expiry, and data sync jobs.',
        depth: ['OAuth connections', 'disconnect', 'sync triggers', 'job history'],
        sidebar: true,
      },
      {
        id: 'webhooks',
        label: 'Webhooks',
        href: '/settings/integrations/webhooks',
        icon: Webhook,
        status: 'wired',
        service: 'integration-service',
        description: 'Outbound webhook subscriptions, signing secrets, and delivery logs.',
        depth: ['subscriptions', 'signing secrets', 'delivery log', 'replay'],
        sidebar: true,
      },
      {
        id: 'company-profile',
        label: 'Company',
        href: '/settings/company',
        icon: Building2,
        status: 'wired',
        service: 'auth-service',
        description: 'Company identity, contact details, address, and localization.',
        depth: ['profile', 'address', 'logo', 'timezone', 'currency'],
        sidebar: true,
        adminOnly: true,
      },
      {
        id: 'org-structure',
        label: 'Org Structure',
        href: '/settings/org-structure',
        icon: Network,
        status: 'wired',
        service: 'auth-service',
        description: 'Departments (tree) and seniority levels for your organization.',
        depth: ['department tree', 'department head', 'seniority levels', 'ranks'],
        sidebar: true,
        adminOnly: true,
      },
      {
        id: 'org-chart',
        label: 'Org Chart',
        href: '/org-chart',
        icon: Users,
        status: 'wired',
        service: 'auth-service',
        description: 'Reporting hierarchy across the organization, read-only.',
        depth: ['reporting tree', 'direct reports', 'titles', 'departments'],
        sidebar: true,
      },
      {
        id: 'users',
        label: 'Users',
        href: '/settings/users',
        icon: Users,
        status: 'wired',
        service: 'auth-service',
        description: 'Invite users, role assignment, status, and account management.',
        depth: ['invites', 'role assignment', 'activation', 'reset actions'],
        sidebar: true,
        adminOnly: true,
      },
      {
        id: 'roles',
        label: 'Roles',
        href: '/settings/roles',
        icon: Lock,
        status: 'wired',
        service: 'auth-service',
        description: 'Role definitions, permissions matrix, RBAC configuration, and admin controls.',
        depth: ['roles', 'permission matrix', 'RBAC', 'system role protection'],
        sidebar: true,
      },
      {
        id: 'system-status',
        label: 'System Status',
        href: '/status',
        icon: Activity,
        status: 'ready',
        service: 'web, all services',
        description: 'Live per-service health board polled from each service /health endpoint.',
        depth: ['per-service up/degraded/down', 'latency', 'auto-refresh', 'health summary'],
        sidebar: true,
        adminOnly: true,
      },
    ],
  },
  {
    id: 'configuration',
    label: 'Configuration & Data',
    icon: Settings2,
    description: 'Data model, pipelines, finance setup, privacy, and record governance.',
    modules: [
      {
        id: 'custom-fields',
        label: 'Custom Fields',
        href: '/settings/custom-fields',
        icon: Database,
        status: 'wired',
        service: 'crm-service, metadata-service',
        description: 'Low-code entity fields, user-created data model extension, and validation hooks.',
        depth: ['entity fields', 'field types', 'validation', 'metadata extension'],
        sidebar: true,
      },
      {
        id: 'module-builder',
        label: 'Module Builder',
        href: '/settings/modules',
        icon: Boxes,
        status: 'wired',
        service: 'metadata-service',
        description: 'Low-code module designer: custom modules, fields, Canvas layouts, and record data models.',
        depth: ['custom modules', 'field manager', 'formula fields', 'Canvas layouts', 'dynamic records'],
        sidebar: true,
      },
      {
        id: 'scoring-rules',
        label: 'Scoring Rules',
        href: '/settings/scoring-rules',
        icon: Target,
        status: 'wired',
        service: 'crm-service',
        description: 'Deterministic lead scoring rules, signals, points, and activation.',
        depth: ['signals', 'points', 'active toggles', 'scoring engine inputs'],
        sidebar: true,
      },
      {
        id: 'pipelines-settings',
        label: 'Pipeline Settings',
        href: '/settings/pipelines',
        icon: Layers,
        status: 'wired',
        service: 'crm-service',
        description: 'Pipeline definitions, stages, default pipeline, and sales process setup.',
        depth: ['pipeline definitions', 'stage setup', 'default pipeline', 'process control'],
        sidebar: true,
      },
      {
        id: 'tax-currency',
        label: 'Tax & Currency',
        href: '/settings/tax',
        icon: DollarSign,
        status: 'wired',
        service: 'finance-service',
        description: 'Tax zones, tax rates, currencies, exchange rates, and finance localization.',
        depth: ['tax zones', 'tax rates', 'currency setup', 'exchange rates'],
        sidebar: true,
      },
      {
        id: 'quote-admin',
        label: 'Quote Administration',
        href: '/settings/quotes',
        icon: FileText,
        status: 'wired',
        service: 'finance-service',
        description: 'Admin-controlled quote numbering (prefix/padding/reset) and multi-level approval thresholds.',
        depth: ['auto numbering', 'approval tiers', 'discount thresholds', 'sequence control'],
        sidebar: true,
        adminOnly: true,
      },
      {
        id: 'sso',
        label: 'Single Sign-On',
        href: '/settings/sso',
        icon: ShieldCheck,
        status: 'wired',
        service: 'auth-service',
        description: 'SAML/SSO configuration, metadata, toggles, and tenant authentication policy.',
        depth: ['SAML metadata', 'SSO config', 'tenant toggles', 'auth policy'],
        sidebar: true,
      },
      {
        id: 'data-privacy',
        label: 'Data Privacy',
        href: '/settings/data-privacy',
        icon: Lock,
        status: 'preview',
        service: 'auth-service, crm-service',
        description: 'Ownership transfer, privacy actions, and compliance controls.',
        depth: ['ownership transfer', 'privacy requests', 'consent controls', 'data governance'],
        sidebar: true,
      },
      {
        id: 'gdpr',
        label: 'GDPR',
        href: '/settings/gdpr',
        icon: ShieldCheck,
        status: 'wired',
        service: 'auth-service, workflow-service',
        description: 'Erasure requests, privacy workflows, data ownership, and compliance tracking.',
        depth: ['erasure requests', 'GDPR workflow', 'data ownership', 'audit readiness'],
        sidebar: true,
      },
      {
        id: 'duplicates',
        label: 'Duplicates',
        href: '/settings/duplicates',
        icon: GitBranch,
        status: 'wired',
        service: 'crm-service',
        description: 'Duplicate scan, merge, dedup groups, and data quality operations.',
        depth: ['dedup scan', 'merge actions', 'duplicate groups', 'data quality'],
        sidebar: true,
      },
      {
        id: 'recycle-bin',
        label: 'Recycle Bin',
        href: '/recycle-bin',
        icon: Recycle,
        status: 'wired',
        service: 'crm-service',
        description: 'Soft-deleted records, recovery, archive controls, and retention workflow.',
        depth: ['soft delete', 'restore', 'archive control', 'retention'],
        sidebar: true,
      },
    ],
  },
];

// A handful of modules are intentionally listed under more than one group in
// CRM_MODULE_GROUPS (e.g. `/quotes`, `/approvals`, `/settings/quote-automation`
// appear in both a domain group and an admin group). Flattening naively would
// count and render those twice — the source of the "data duplicated in the UI"
// report (duplicate system-map cards, inflated module totals). Dedupe by `href`,
// keeping the first occurrence, so every distinct module surfaces exactly once.
export const CRM_MODULES = (() => {
  const seen = new Set<string>();
  return CRM_MODULE_GROUPS.flatMap((group) =>
    group.modules
      .filter((module) => {
        if (seen.has(module.href)) return false;
        seen.add(module.href);
        return true;
      })
      .map((module) => ({ ...module, groupId: group.id, groupLabel: group.label }))
  );
})();

export const CRM_SERVICE_NAMES = [
  'accounts-service',
  'activities-service',
  'analytics-service',
  'approval-service',
  'auth-service',
  'blueprint-service',
  'cadence-service',
  'chatbot-service',
  'comm-service',
  'contacts-service',
  'crm-service',
  'data-service',
  'deals-service',
  'document-service',
  'email-sync-service',
  'finance-service',
  'graphql-gateway',
  'incentive-service',
  'integration-service',
  'knowledge-service',
  'leads-service',
  'metadata-service',
  'notes-service',
  'notification-service',
  'planning-service',
  'portal-service',
  'quotes-service',
  'realtime-service',
  'reporting-service',
  'search-service',
  'storage-service',
  'territory-service',
  'workflow-service',
];
