[SERVICE]
    Flush        1
    Log_Level    info
    Daemon       off
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Tag               nexus.*
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    DB                /tmp/fluent-bit.db
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On
    Refresh_Interval  10

[FILTER]
    Name   grep
    Match  nexus.*
    Regex  log .*

[FILTER]
    Name          parser
    Match         nexus.*
    Key_Name      log
    Parser        json
    Reserve_Data  On

[OUTPUT]
    Name            opensearch
    Match           nexus.*
    Host            opensearch
    Port            9200
    Index           nexus-logs
    Type            _doc
    Suppress_Type_Name On
    Trace_Error     On
